### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by MesterPerfect** [hxebolax/Add-on-packer#11]
hi
A correction to Arabic language phrases has been sent via Pull requests
The translation of the addendum into Spanish has also been sent
Why weren't Pull requests accepted or responded to?

**Comment by hxebolax** [comment]
Hi, I don't have any Pull requests for Arabic language.

I only have one in Ukrainian which has just been approved and another Russian one from last year which I didn't accept because I already have a translation from the Russian community of nvda.ru.

Please send me the Pull requests again because I don't get it here.

Regards.

**Comment by MesterPerfect** [comment]
> Hi, I don't have any Pull requests for Arabic language.
> 
> I only have one in Ukrainian which has just been approved and another Russian one from last year which I didn't accept because I already have a translation from the Russian community of nvda.ru.
> 
> Please send me the Pull requests again because I don't get it here.
> 
> Regards.

hi
When you was late in answering I deleted it because I thought you didn't update the add-on again
I have opened a new Pull requests
https://github.com/hxebolax/Add-on-packer/pull/13
Regards.
